---
title: "Report"
output: 
  html_document:
---

<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<style>
body {
  font-size: 16px;
  font-family: 'Roboto', sans-serif;
  line-height: 2.0;
}

p::first-letter {
  font-size: 200%;
  font-weight: bold;
  color: blue;
}
</style>


  The goal of our dataset is to see where most of the right sightings are within New York City. Additionally, we know that rats are significant within New York City, and seeing where they like to hang out would be crucial information for our knowledge. However, many New Yorkers know that the rats are a big problem here. They are overpopulated here about three million rats currently live within NYC and on average they are bigger compared to other rats ranging form 16 inches to 20 inches. Back in April 20223, Rat Czar was implemented to help decrease the rat infestation that was happening within the city. Within our database we wanted to see if it was actually effective or not because we know these rats can be tricky to kill off. 

  In our honest opionon, we consider the rats as the unofficial mascot of New York City due to their significance and history here. When people think of New York City, they probably think about Time Square, the Statue of Liberty and the Rats! Since all of us moved here in New York City, we have never experienced seeing so many rats crawling and running around oiu neighborhood before especially ones that are so big. Furthermore, who can forget the infamous pizza rat where a rat was carrying a slice of pizza up the stair way at the subway. This just further shows that New York City rats are a whole different species and no other rats can be compared to them. We also know that these rodents can carry many harmul diseases that can affect the human qualit life. Furthermore, these diseases can contaiminate onto our food supply by the rats. The infrastructure of our buildings could also be at risk due to the rats gnawing and burrowing. Even though these guys are infamously around New York, it is most important that they are kept under control, so no one is harmed by them. 

  Within this dataset, we wanted to see which boroughs and areas had the most prevalent rat sightings. It would just be interesting information to see where they like to hang out at and when we find apartments next year we can avoid areas with high rat sightings. Furthermore, we wanted to see the effectiveness of Rat Czar and see if there a difference, so we are not wasting money into the program. Covid-19 was another factor we wanted to see if it played a role on rat sighting. Would social distancing affect the rats in any type of way. We also wanted to see if location type would affect the amount of times we would see the rats. 

  The data that we used was from NYC open data which keeps track of all the reported rat sightings. The dataset is constantly being updated with new rat sightings being added every day. Firstly we used the clean janitor function to reformat the name of our columns. Then the data was cleaned by filtering for dates, the dates that we wanted to look was from the year 2019 to 2023, the reason for this is that wanted data before and after Covid-19 to see if there were any differences. We also wanted to see if Rat Czar was effective as well which was implemented in April 2023. 

  Within our dataset, we originally wanted to do a regression on the difference of location type to see what type of location was more likely to have rat sightings. However, after many attempts on trying to manipulating the data, we realized that we could not do a regression analysis due to the fact that our data was descriptive and it only includes rat sightings which can’t be compared to anything else. Within the dataset, there isn’t any other numeric variable that we can used to make an analysis on. We decided to not include an anlsyis on the data. The visualizaitons that we used was looking at a map with the  population density of the rats sighting within all five boroughs in the year 2023. We looked at months of March and November because it was the month before the Rat Czar was implemented and this would give us a good idea if the program is working on reducing the rat infestation. We also looked at the population density of the rat sightings throughout the whole year of 2023. We looked at the monthly 
