---
title: "P8105 Final Project"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
library(tidyverse)
library(patchwork)
library(ggplot2)
library(ggmap)
library(osmdata)

knitr::opts_chunk$set(
  echo = TRUE,
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Preliminary data import and cleaning:

```{r}
rats_df = 
  read_csv("./data/rat_sightings.csv") %>% 
  janitor::clean_names() %>% 
  select(unique_key, created_date, location_type, incident_zip, city, borough, latitude, longitude, location) %>% 
  separate(created_date, into = c("created_date", "time"), sep = " ") %>% 
  separate(created_date, into = c("month", "day", "year"), sep = "/")
```



## Making the density map
```{r}
head(rats_df)
```

```{r}
nyc_map <- get_stadiamap(bbox = c(left = -74.26, bottom = 40.5, right = -73.7, top = 40.9),zoom=10)


ggmap(nyc_map)
```

```{r}

rats_march=rats_df|>
  filter(month %in% "01", 
         year%in% "2023")|>
  filter(borough != "Unspecified")

ggmap(nyc_map)+
geom_point(aes(x=longitude,y=latitude,color=borough),alpha=0.3,data=rats_march)+
  theme_minimal() +
  labs(title = "Population Density Map as of March 2023")




```

```{r}
rats_november=rats_df|>
  filter(month %in% "11", 
         year%in% "2023")|>
  filter(borough != "Unspecified")

ggmap(nyc_map)+
geom_point(aes(x=longitude,y=latitude,color=borough),alpha=0.3,data=rats_march)+
  theme_minimal() +
  labs(title = "Population Density Map as of November 2023")




```

```{r fig.height=10, fig.width=12}
rats_2023=rats_df|>
  filter(year %in% "2023")|>
  drop_na()|>
  ggplot(aes(x=longitude,y=latitude))+
  theme_minimal() +
  labs(title = "Population Density Map as of 2023")+
  geom_point(aes(color=borough,alpha=0.3))+
  facet_wrap(~ month, scales = "fixed", ncol = 6)
  
rats_2023
```



## Regression analyses

```{r}
rats_df
```







