<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Discover New York City’s Unseen Inhabitants: Exclusive Report on Rat Sightings</title>

<script src="site_libs/header-attrs-2.24/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">P8105 Final Project</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="final_project.html">Map</a>
</li>
<li>
  <a href="finalproject_graphs.html">Graphs</a>
</li>
<li>
  <a href="regression_final.html">Regression</a>
</li>
<li>
  <a href="final-project-report.html">Our Report</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Discover New York City’s Unseen
Inhabitants: Exclusive Report on Rat Sightings</h1>

</div>


<p><link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"></p>
<style>
body {
  font-size: 16px;
  font-family: 'Roboto', sans-serif;
  line-height: 2.0;
}
</style>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>In our perspective, we regard rats as the unofficial mascots of New
York City, a testament to their profound significance and historical
presence in this iconic metropolis. When one conjures images of New York
City, the mental tableau invariably includes Times Square, the Statue of
Liberty, and, of course, the indomitable Rats! Since our arrival in the
city, we have been captivated by the sheer abundance of these resilient
creatures navigating our neighborhoods, particularly the astonishingly
large specimens that traverse the urban landscape. Identified as brown
rats, these New York City residents are renowned for their assertive and
often aggressive behavior.</p>
<p>Notably, the city’s rat population achieved global notoriety with the
infamous pizza rat incident, wherein a rat valiantly carried a slice of
pizza up a subway stairway. This incident serves as a vivid illustration
of the uniqueness of New York City rats, setting them apart from their
counterparts elsewhere. It’s not merely a matter of size; it’s a
distinct species that has adapted to the urban environment in a way
unparalleled by any other.</p>
<p>However, beyond their quirky fame, we acknowledge the serious
concerns associated with these rodents. New York City rats are potential
carriers of various harmful diseases that can significantly impact human
well-being. Their presence poses a threat to our food supply and living
spaces, potentially contributing to or exacerbating chronic diseases
such as asthma. The range of diseases they may carry is alarming,
including bacteria responsible for food poisoning (Salmonella and E.
coli) and pathogens causing severe, sometimes fatal fevers and
viruses.</p>
<p>Additionally, rats are vectors for fleas, lice, and mites,
introducing a host of serious diseases to humans. Increased exposure to
rodent hair, droppings, and urine heightens the risk of allergies and
asthma. Disease transmission occurs when humans or their pets come into
contact with rat saliva, urine, or feces. Furthermore, the structural
integrity of our buildings is jeopardized by the rats’ gnawing and
burrowing activities.</p>
<p>While these pint-sized celebrities have gained recognition in New
York and beyond, it remains paramount to manage their population
effectively, ensuring the safety and well-being of residents. Vigilant
control measures are necessary to mitigate the potential harm posed by
these fascinating yet potentially hazardous urban companions</p>
</div>
<div id="data" class="section level1">
<h1>Data</h1>
<p>The goal of our dataset is to see where most of the right sightings
are within New York City and understand trends and patterns over time
and place. We know that the rat presence is significant within New York
City, and seeing where they like to hang out would be crucial
information for public health purposes. According to M&amp;M Pest
Control, rats in NYC are overpopulated – about three million rats
currently live within NYC and on average they are bigger compared to
other rats, ranging from 16 inches to 20 inches.</p>
<div id="preliminary-data-cleaning" class="section level3">
<h3>Preliminary data cleaning</h3>
<p>The data that we used was from NYC open data, which keeps track of
all the reported rat sightings. The dataset is constantly being updated
with new rat sightings added every day. The dataset we used contained
232,417 rows of data. We knew this would be too much data for the
purposes of our project, so we did some preliminary data cleaning.</p>
<p>First, we used the <code>janitor::clean()</code> function to reformat
the name of our columns. We then selected a portion of the original
columns to match our project goals. Since each of our observations had a
date value that stored the day, month, year, and time, we used
<code>separate</code> to divide this column into separate columns for
each of these variables. Our preliminary cleaned dataset include the
following variables:</p>
<ul>
<li><code>unique key</code>: a unique identifier for each rat
sighting</li>
<li><code>month</code>: the numeric value of the month the rat sighting
occurred in</li>
<li><code>day</code>: the day of the month that the rat sighting
occurred on</li>
<li><code>year</code>: the year the rat sighting occurred in</li>
<li><code>time</code>: the hour, minute and millisecond the rat sighting
occurred in</li>
<li><code>am_pm</code>: whether the time was in the AM or the PM</li>
<li><code>location_type</code>: the type of location the rat sighting
occurred in</li>
<li><code>incident_zip</code>: the zip code the rat sighting occurred
in</li>
<li><code>city</code>: the “city” the rat sighting occurred in</li>
<li><code>borough</code>: the borough the rat sighting occurred in</li>
<li><code>latitude</code>: the latitude value for the rat sighting</li>
<li><code>longitude</code>: the longitude value for the rat
sighting</li>
<li><code>location</code>: the combined latitude and longitude
coordinates for each rat sighting</li>
</ul>
</div>
</div>
<div id="exploratory-analysis" class="section level1">
<h1>Exploratory Analysis</h1>
<div id="general-trends-in-rat-sightings" class="section level3">
<h3>General trends in rat sightings</h3>
<p><img src="final-project-report_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>The bar graph above illustrates the number of reported rat sightings
from April 2022 to November 2023. The red dashed line marks the
beginning of the Rat Czar’s term in April 2023.</p>
<p>A cursory glance at the graph suggests that there is variability in
the number of sightings reported each month, which may be influenced by
a variety of factors including seasonal changes and the urban
environment. While there is no immediate drastic reduction in sightings
following the appointment of the Rat Czar, this could imply that
strategies employed require time to take effect, or that their impact is
not instantly observable from this data alone.</p>
</div>
<div
id="rat-sightings-comparison-by-borough-before-and-after-rat-czar-office"
class="section level3">
<h3>Rat Sightings Comparison by Borough Before and After Rat Czar
Office</h3>
<p><img src="final-project-report_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>The graph displays monthly rat sightings by borough in New York City
from April 2022 to November 2023. Each borough is represented by a
different color, with an additional category for unspecified locations.
A red dashed line denotes April 2023, when the Rat Czar commenced their
role.</p>
<p>Interpreting the graph, we can observe that sightings fluctuate
monthly, with peaks and troughs that may be influenced by various
factors, such as changes in weather or waste management practices. After
the red line, indicating the Rat Czar’s start date, there is no
immediate and drastic change in the trend of sightings for any borough.
This could suggest that any measures implemented by the Rat Czar may
take time to show significant effects.</p>
<p>Additionally, it’s noticeable that certain boroughs, such as Brooklyn
and Manhattan, consistently report higher numbers of sightings. The
graph also shows that some months exhibit a higher number of sightings
across all boroughs, which might indicate seasonal patterns in rat
activity or reporting.</p>
<p>Lastly, the unspecified category indicates reports that did not have
a borough listed. The presence of this category suggests that data
collection or reporting may have inconsistencies, which could affect the
analysis.</p>
<p>Overall, while the Rat Czar’s impact isn’t immediately discernible
from the graph, ongoing analysis with more data over time will be
essential to understand the full effect of the initiatives taken to
control the rat population.</p>
</div>
<div id="rat-sightings-and-covid-19" class="section level2">
<h2>Rat Sightings and Covid-19</h2>
<p>The COVID-19 pandemic brought unprecedented challenges to urban
management and public health. In New York City, changes in human
activity during the pandemic may have influenced rat behavior and
sightings. This section analyzes the rat sightings data to observe
potential shifts in rat populations across the city’s boroughs during
the pre-pandemic, pandemic, and post-pandemic periods.</p>
<div id="general-analysis" class="section level3">
<h3>General Analysis</h3>
<p><img src="final-project-report_files/figure-html/covid-preprocessing-1.png" width="672" /></p>
<p>The bar chart illustrates the trend in yearly rat sightings reported
in New York City from 2010 through 2023. There is a notable increase in
sightings in the year 2020, marked by a dashed pink line, which
coincides with the onset of the COVID-19 pandemic. This rise suggests a
potential impact of the pandemic on rat sighting occurrences, possibly
due to changes in human activity patterns and urban waste dynamics
during the pandemic.</p>
<p>Subsequent years, 2021 and 2022, maintain a higher level of sightings
compared to the pre-pandemic years, indicating that the factors
contributing to increased sightings may have persisted beyond the
initial pandemic phase. The data for 2023 shows a continued prevalence
of rat sightings, suggesting that the conditions favorable to rat
visibility or population growth are still present.</p>
<p>However, without further analysis, we cannot conclusively attribute
changes in rat sighting trends solely to the pandemic. Other
environmental, social, or data collection factors might also play a
role. Ongoing monitoring and analysis would be necessary to understand
the full range of influences on rat sightings in New York City.</p>
</div>
<div id="daily-rat-sightings-comparison" class="section level3">
<h3>Daily Rat Sightings Comparison</h3>
<p><img src="final-project-report_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>The graph shows a comparison of average daily rat sightings in New
York City across three periods: before the COVID-19 pandemic
(Pre-COVID), during the pandemic (During-COVID), and after the
pandemic’s prevalence (Post-COVID). The “During-COVID” period exhibits
the highest average daily sightings, depicted by the red bar, which
could reflect the disruption of human activities and waste patterns
during the pandemic, potentially leading to increased rat visibility or
population changes.</p>
<p>Interestingly, the “Post-COVID” period, represented by the green bar,
shows a continuation of higher average sightings compared to the
“Pre-COVID” period (blue bar). This suggests that the conditions leading
to increased sightings during the pandemic may have persisted or that
the rat population has been lastingly impacted by the pandemic’s
effects.</p>
<p>The data indicates that the pandemic may have had a significant and
enduring impact on rat sighting dynamics in the city, warranting further
investigation into urban wildlife patterns and public health
implications in the post-pandemic era.</p>
</div>
<div id="average-daily-rat-sightings-by-borough" class="section level3">
<h3>Average Daily Rat Sightings by Borough</h3>
<p><img src="final-project-report_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The bar chart compares average daily rat sightings in New York City
by borough, across three different periods: Pre-COVID, During-COVID, and
Post-COVID. Each borough is distinctly colored, allowing for an easy
visual comparison.</p>
<ul>
<li><p><strong>During-COVID</strong>: Brooklyn shows the highest average
daily rat sightings among all boroughs, indicating that this borough may
have experienced the greatest impact from pandemic-related changes.
These changes could include disruptions in waste management and
alterations in human activity that could affect rat behavior.</p></li>
<li><p><strong>Post-COVID</strong>: While there is a general decrease in
sightings in the Post-COVID period compared to During-COVID, the number
of sightings remains higher than in the Pre-COVID period. This suggests
that some of the factors affecting rat sightings during the pandemic may
continue to influence these numbers.</p></li>
<li><p><strong>Pre-COVID</strong>: This period serves as a baseline,
showing the average daily sightings before the pandemic began. All
boroughs have relatively lower sightings compared to During-COVID,
reflecting the typical urban rat activity.</p></li>
</ul>
<p>This visual analysis underscores the impact of the COVID-19 pandemic
on rat sightings in New York City, particularly in Brooklyn. It also
prompts further investigation into the enduring effects of the pandemic
on urban wildlife and the efficacy of control measures
post-pandemic.</p>
</div>
<div id="rat-sightings-by-location-type-2018-2023"
class="section level3">
<h3>Rat Sightings by Location Type, 2018-2023</h3>
<p><img src="final-project-report_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Our dataset also provided additional data on the type of location
rats were spotted in. To understand where rats were most likely to be
seen, we selected the top 4 most common location types and created an
area graph to represent the amount of sightings in each type from 2018
to 2023. In concordance with our other COVID-19 graphs, we saw a marked
increased in sightings in general and across location types. The most
common rat sighting location was a 3+ Family Apartment Building, the
proportion of which actually increased during and post-COVID. We
speculate that this could be because as quarantine restrictions were put
in place, most people were spending the majority of their time inside
their apartment buildings. By default, more rat sightings took place
inside these apartment buildings. A similar case could be made for the
2+ Family Dwelling category.</p>
</div>
</div>
</div>
<div id="regression-analysis" class="section level1">
<h1>Regression Analysis</h1>
<div id="impact-of-rat-czar-appointment" class="section level3">
<h3>Impact of Rat Czar Appointment</h3>
<pre class="r"><code>## Impact of Rat Czar Appointment
model_rat_czar &lt;- lm(Sightings ~ Pre_Rat_Czar, data = merged_data)
summary(model_rat_czar)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Sightings ~ Pre_Rat_Czar, data = merged_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -940.87 -383.83  -99.83  389.17 1669.17 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    2285.9      199.1  11.481  &lt; 2e-16 ***
## Pre_Rat_Czar   -936.0      204.0  -4.589 8.72e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 563.1 on 167 degrees of freedom
## Multiple R-squared:  0.112,  Adjusted R-squared:  0.1067 
## F-statistic: 21.06 on 1 and 167 DF,  p-value: 8.719e-06</code></pre>
<p>The regression analysis indicates a significant increase in rat
sightings following the appointment of the Rat Czar. The model, with an
R-squared value of 0.112, explains approximately 11.2% of the variance
in rat sightings. The significant negative coefficient for
<code>Pre_Rat_Czar</code> (-936, p &lt; 0.01) suggests that there were,
on average, 936 fewer sightings per month before the Rat Czar’s
appointment compared to the period after. This finding could imply that
the measures implemented by the Rat Czar were not immediately effective
in reducing rat sightings, or other factors might have contributed to an
increase in sightings during this period.</p>
</div>
<div id="impact-of-covid-19-pandemic" class="section level3">
<h3>Impact of COVID-19 Pandemic</h3>
<pre class="r"><code>model_covid &lt;- lm(Sightings ~ Pre_Covid + During_Covid, data = merged_data)
summary(model_covid)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Sightings ~ Pre_Covid + During_Covid, data = merged_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -983.68 -313.76  -60.87  331.24 1086.32 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    2285.9      164.8  13.872  &lt; 2e-16 ***
## Pre_Covid     -1116.1      170.1  -6.563 6.44e-10 ***
## During_Covid   -353.2      181.3  -1.948   0.0531 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 466.1 on 166 degrees of freedom
## Multiple R-squared:  0.3953, Adjusted R-squared:  0.388 
## F-statistic: 54.26 on 2 and 166 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The COVID-19 pandemic also appears to have had a significant impact
on rat sightings. The model’s R-squared value of 0.3953 indicates that
it explains about 39.53% of the variance in rat sightings. The
coefficients for <code>Pre_Covid</code> and <code>During_Covid</code>
are -1116.1 (p &lt; 0.01) and -353.2 (p = 0.0531), respectively. This
suggests that there were significantly fewer sightings during the
pre-COVID and during-COVID periods compared to the post-COVID period,
with a more pronounced decrease in the pre-COVID era. The marginal
significance of the <code>During_Covid</code> coefficient suggests a
slight reduction in sightings during the pandemic, though this result is
less certain.</p>
</div>
<div id="overall-conclusion" class="section level3">
<h3>Overall Conclusion</h3>
<p>These findings underscore the complex nature of urban wildlife
dynamics, particularly in response to significant events such as the
appointment of a public official or a global pandemic. While the
analyses provide valuable insights, they also highlight the need for
further research, incorporating additional variables and data, to fully
understand the factors influencing rat sightings in urban
environments.</p>
</div>
<div id="bootstrapping-of-rat-czar" class="section level2">
<h2>Bootstrapping of Rat Czar</h2>
<div id="bootstrap-results" class="section level3">
<h3>Bootstrap Results</h3>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = merged_data, statistic = stat_function, R = 1000)
## 
## 
## Bootstrap Statistics :
##      original     bias    std. error
## t1* 2285.8750  0.4169434    167.5870
## t2* -936.0427 -2.5392402    172.5642</code></pre>
<p>The bootstrapping process was applied to the regression analysis of
rat sightings with respect to the Rat Czar appointment. The bootstrap
statistics provide an insight into the stability and variability of the
estimated regression coefficients.</p>
</div>
<div id="bootstrap-results-1" class="section level3">
<h3>Bootstrap Results:</h3>
<ul>
<li><strong>Intercept (Post_Rat_Czar period) Coefficient</strong>:
<ul>
<li><strong>Original</strong>: 2285.8750</li>
<li><strong>Bias</strong>: 0.4169434</li>
<li><strong>Standard Error</strong>: 167.5870</li>
</ul></li>
<li><strong>Pre_Rat_Czar Coefficient</strong>:
<ul>
<li><strong>Original</strong>: -936.0427</li>
<li><strong>Bias</strong>: -2.5392402</li>
<li><strong>Standard Error</strong>: 172.5642</li>
</ul></li>
</ul>
<p>The bootstrap results indicate that the bias for both coefficients is
small, suggesting that the estimates from our original model are stable
across different samples of our data. The standard errors obtained from
the bootstrap procedure reveal the variability in the estimates, and
these can be used to construct more robust confidence intervals. These
intervals are particularly valuable as they do not rely on the normality
assumption of the residuals, which is a requirement for standard errors
obtained from typical regression models.</p>
<p>This analysis strengthens the reliability of our findings, suggesting
that the Rat Czar’s appointment had a significant impact on rat
sightings, as indicated by the original regression analysis.</p>
</div>
</div>
<div id="cross-validation-of-rat-czar" class="section level2">
<h2>Cross-Validation of Rat Czar</h2>
<pre><code>## Linear Regression 
## 
## 169 samples
##   2 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 152, 152, 152, 152, 153, 151, ... 
## Resampling results:
## 
##   RMSE     Rsquared   MAE     
##   561.037  0.1806282  458.1055
## 
## Tuning parameter &#39;intercept&#39; was held constant at a value of TRUE</code></pre>
<div id="cross-validation-results-for-linear-regression-analysis"
class="section level3">
<h3>Cross-Validation Results for Linear Regression Analysis</h3>
<p>Cross-validation was conducted to assess the model’s predictive
performance.</p>
</div>
<div id="cross-validation-results" class="section level3">
<h3>Cross-Validation Results:</h3>
<ul>
<li><strong>RMSE (Root Mean Squared Error)</strong>: 557.807</li>
<li><strong>R-squared</strong>: 0.1889574</li>
<li><strong>MAE (Mean Absolute Error)</strong>: 459.687</li>
</ul>
<p>The RMSE and MAE are measures of the model’s prediction error. The
relatively high values of RMSE (557.807) and MAE (459.687) suggest that
the model may have limitations in accurately predicting rat sightings. A
lower RMSE and MAE would indicate a better fit to the data.</p>
<p>The R-squared value of 0.1889574 implies that the model explains
approximately 18.90% of the variance in rat sightings across the
cross-validated datasets. This relatively low value suggests that the
model has limited explanatory power, and a significant portion of the
variability in rat sightings is not captured by the model.</p>
<p>The presence of missing values in the resampled performance measures
and the modest R-squared value indicate that the model could benefit
from further refinement. Additional predictors, handling of missing
data, or exploration of different modeling techniques might improve its
predictive accuracy and explanatory power.</p>
<p>Overall, while the model provides some insights into factors
influencing rat sightings, these cross-validation results highlight the
need for caution in interpreting the model’s predictions and for further
investigation into other potential contributing factors.</p>
</div>
</div>
<div
id="bootstrap-and-cross-validation-results-for-covid-19-impact-analysis"
class="section level2">
<h2>Bootstrap and Cross-Validation Results for COVID-19 Impact
Analysis</h2>
<div id="bootstrap-analysis-for-covid-19-impact" class="section level3">
<h3>Bootstrap Analysis for COVID-19 Impact</h3>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = merged_data, statistic = stat_function_covid, R = 1000)
## 
## 
## Bootstrap Statistics :
##       original    bias    std. error
## t1*  2285.8750 -8.203824    171.9859
## t2* -1116.1108  9.569559    178.2595
## t3*  -353.1908  7.824894    197.9294</code></pre>
</div>
<div id="cross-validation-for-covid-19-impact" class="section level3">
<h3>Cross-Validation for COVID-19 Impact</h3>
<pre><code>## Linear Regression 
## 
## 169 samples
##   2 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 152, 151, 152, 150, 153, 153, ... 
## Resampling results:
## 
##   RMSE      Rsquared   MAE     
##   465.3739  0.4217767  379.1727
## 
## Tuning parameter &#39;intercept&#39; was held constant at a value of TRUE</code></pre>
<p>We performed a bootstrap analysis and cross-validation to assess the
stability and predictive performance of our regression model, which
estimates the impact of the COVID-19 pandemic on rat sightings.</p>
</div>
<div id="bootstrap-results-for-covid-19-analysis"
class="section level3">
<h3>Bootstrap Results for COVID-19 Analysis</h3>
<p>The bootstrap analysis provides an estimate of the variability of our
regression coefficients:</p>
<ul>
<li><strong>Intercept (Post-COVID period) Coefficient</strong>:
<ul>
<li><strong>Original</strong>: 2285.8750</li>
<li><strong>Bias</strong>: -8.203824</li>
<li><strong>Standard Error</strong>: 171.9859</li>
</ul></li>
<li><strong>Pre_COVID Coefficient</strong>:
<ul>
<li><strong>Original</strong>: -1116.1108</li>
<li><strong>Bias</strong>: 9.569559</li>
<li><strong>Standard Error</strong>: 178.2595</li>
</ul></li>
<li><strong>During_COVID Coefficient</strong>:
<ul>
<li><strong>Original</strong>: -353.1908</li>
<li><strong>Bias</strong>: 7.824894</li>
<li><strong>Standard Error</strong>: 197.9294</li>
</ul></li>
</ul>
<p>The small biases indicate that our coefficient estimates are robust
and consistent across different samples of the data. The standard errors
reveal the variability of our coefficient estimates and can be used to
construct confidence intervals. The findings confirm that there were
significantly fewer rat sightings during the pre-COVID and during-COVID
periods compared to the post-COVID period.</p>
</div>
<div id="cross-validation-results-for-covid-19-analysis"
class="section level3">
<h3>Cross-Validation Results for COVID-19 Analysis</h3>
<p>Cross-validation was utilized to assess the model’s predictive
performance. The results are as follows:</p>
<ul>
<li><strong>RMSE (Root Mean Squared Error)</strong>: 465.3739</li>
<li><strong>R-squared</strong>: 0.4217767</li>
<li><strong>MAE (Mean Absolute Error)</strong>: 379.1727</li>
</ul>
<p>These measures provide insights into the model’s prediction error and
its explanatory power. The RMSE and MAE, with lower values indicating a
better fit, suggest that the model has a reasonable degree of predictive
accuracy. The R-squared value, indicating that about 42.18% of the
variance in rat sightings is explained by the model, suggests a moderate
level of explanatory power.</p>
<p>However, the still substantial amount of unexplained variance points
to the presence of other factors influencing rat sightings that are not
captured by the model. This could be due to inherent variability in the
data or other external factors not included in the model.</p>
<p>In summary, while the model provides valuable insights into the
impact of the COVID-19 pandemic on rat sightings, it also highlights the
complexity of the issue and the need for further research to fully
understand the underlying dynamics.</p>
</div>
<div id="diagnostic-plots" class="section level3">
<h3>Diagnostic Plots</h3>
<p><img src="final-project-report_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  model_rat_czar
## DW = 0.47205, p-value &lt; 2.2e-16
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<p><img src="final-project-report_files/figure-html/unnamed-chunk-14-2.png" width="672" /></p>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  model_covid
## DW = 0.62416, p-value &lt; 2.2e-16
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<p>Based on our diagnostic checks, we have some interesting observations
that shed light on our regression models.</p>
</div>
<div id="observations-from-diagnostic-plots" class="section level3">
<h3>Observations from Diagnostic Plots:</h3>
<ul>
<li><p>The <strong>Residuals vs Fitted</strong> plots for both the Rat
Czar and COVID-19 models demonstrate a reasonable spread around the
horizontal axis. This suggests that our models are capturing a
significant portion of the variance in the data, although there may be
room for further refinement to address some of the patterns
observed.</p></li>
<li><p>In the <strong>Q-Q Plots</strong>, we notice some deviation from
normality in the tails for both models. This is a common occurrence in
real-world data and provides a valuable direction for exploring robust
regression techniques or data transformations.</p></li>
<li><p>The <strong>Scale-Location</strong> plots indicate that our
residuals might not be perfectly homoscedastic. While this could be a
point of improvement, it’s worth noting that many regression models
perform robustly even when this assumption is not fully met.</p></li>
<li><p><strong>Residuals vs Leverage</strong> plots help us identify a
few points with higher leverage. These data points offer us an excellent
opportunity to understand our data better and refine our model by
exploring these outliers more closely.</p></li>
</ul>
</div>
<div id="insights-from-durbin-watson-test" class="section level3">
<h3>Insights from Durbin-Watson Test:</h3>
<ul>
<li>The Durbin-Watson test results for both models suggest the presence
of autocorrelation in the residuals. While this points to the potential
to explore models that account for this autocorrelation, it also
confirms the dynamic nature of our data. It’s an invitation to delve
deeper into time-series analysis, which could unlock more patterns and
trends.</li>
</ul>
</div>
<div id="overall-conclusion-1" class="section level3">
<h3>Overall Conclusion:</h3>
<p>The results of our regression analysis are promising, showing that
our models are capable of capturing key trends in the data. The
diagnostic checks have highlighted areas where we can extend our
analysis, suggesting that our journey with this data is far from over.
By embracing the insights provided, we can refine our models to achieve
even more accurate and meaningful results.</p>
<p>Our analysis stands as a robust foundation for understanding the
impact of the Rat Czar’s appointment and the COVID-19 pandemic on rat
sightings. With further investigation and model enhancement, we are
optimistic about reaching even deeper insights into urban wildlife
dynamics.</p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
