<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Delve into the Depths of Data: Unraveling the Impacts of Rat Czar and COVID-19 through Regression Analysis</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">P8105 Final Project</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="final_project.html">Map</a>
</li>
<li>
  <a href="finalproject_graphs.html">Graphs</a>
</li>
<li>
  <a href="regression_final.html">Regression</a>
</li>
<li>
  <a href="final-project-report.html">Our Report</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Delve into the Depths of Data: Unraveling
the Impacts of Rat Czar and COVID-19 through Regression Analysis</h1>

</div>


<div id="regression-analysis" class="section level1">
<h1>Regression Analysis</h1>
<div id="impact-of-rat-czar-appointment" class="section level2">
<h2>Impact of Rat Czar Appointment</h2>
<pre class="r"><code>## Impact of Rat Czar Appointment
model_rat_czar &lt;- lm(Sightings ~ Pre_Rat_Czar, data = merged_data)
summary(model_rat_czar)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Sightings ~ Pre_Rat_Czar, data = merged_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -940.87 -383.83  -99.83  389.17 1669.17 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    2285.9      199.1  11.481  &lt; 2e-16 ***
## Pre_Rat_Czar   -936.0      204.0  -4.589 8.72e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 563.1 on 167 degrees of freedom
## Multiple R-squared:  0.112,  Adjusted R-squared:  0.1067 
## F-statistic: 21.06 on 1 and 167 DF,  p-value: 8.719e-06</code></pre>
<p>The regression analysis indicates a significant increase in rat
sightings following the appointment of the Rat Czar. The model, with an
R-squared value of 0.112, explains approximately 11.2% of the variance
in rat sightings. The significant negative coefficient for
<code>Pre_Rat_Czar</code> (-936, p &lt; 0.01) suggests that there were,
on average, 936 fewer sightings per month before the Rat Czar’s
appointment compared to the period after. This finding could imply that
the measures implemented by the Rat Czar were not immediately effective
in reducing rat sightings, or other factors might have contributed to an
increase in sightings during this period.</p>
</div>
<div id="impact-of-covid-19-pandemic" class="section level2">
<h2>Impact of COVID-19 Pandemic</h2>
<pre class="r"><code>model_covid &lt;- lm(Sightings ~ Pre_Covid + During_Covid, data = merged_data)
summary(model_covid)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Sightings ~ Pre_Covid + During_Covid, data = merged_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -983.68 -313.76  -60.87  331.24 1086.32 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    2285.9      164.8  13.872  &lt; 2e-16 ***
## Pre_Covid     -1116.1      170.1  -6.563 6.44e-10 ***
## During_Covid   -353.2      181.3  -1.948   0.0531 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 466.1 on 166 degrees of freedom
## Multiple R-squared:  0.3953, Adjusted R-squared:  0.388 
## F-statistic: 54.26 on 2 and 166 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The COVID-19 pandemic also appears to have had a significant impact
on rat sightings. The model’s R-squared value of 0.3953 indicates that
it explains about 39.53% of the variance in rat sightings. The
coefficients for <code>Pre_Covid</code> and <code>During_Covid</code>
are -1116.1 (p &lt; 0.01) and -353.2 (p = 0.0531), respectively. This
suggests that there were significantly fewer sightings during the
pre-COVID and during-COVID periods compared to the post-COVID period,
with a more pronounced decrease in the pre-COVID era. The marginal
significance of the <code>During_Covid</code> coefficient suggests a
slight reduction in sightings during the pandemic, though this result is
less certain.</p>
</div>
<div id="overall-conclusion" class="section level2">
<h2>Overall Conclusion</h2>
<p>These findings underscore the complex nature of urban wildlife
dynamics, particularly in response to significant events such as the
appointment of a public official or a global pandemic. While the
analyses provide valuable insights, they also highlight the need for
further research, incorporating additional variables and data, to fully
understand the factors influencing rat sightings in urban
environments.</p>
</div>
</div>
<div id="bootstrapping-of-rat-czar" class="section level1">
<h1>Bootstrapping of Rat Czar</h1>
<div id="bootstrap-results" class="section level2">
<h2>Bootstrap Results</h2>
<pre class="r"><code># Define the statistic function for bootstrapping with only Pre_Rat_Czar
stat_function &lt;- function(data, indices) {
  d &lt;- data[indices, ] # allows bootstrapping to select sample
  fit &lt;- lm(Sightings ~ Pre_Rat_Czar, data = d)
  return(coef(fit))
}

# Apply the bootstrapping with R = 1000 bootstrap replicates
results &lt;- boot(data = merged_data, statistic = stat_function, R = 1000)

print(results)</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = merged_data, statistic = stat_function, R = 1000)
## 
## 
## Bootstrap Statistics :
##      original     bias    std. error
## t1* 2285.8750  0.4169434    167.5870
## t2* -936.0427 -2.5392402    172.5642</code></pre>
</div>
<div id="interpretation-of-bootstrap-results" class="section level2">
<h2>Interpretation of Bootstrap Results</h2>
<p>The bootstrapping process was applied to the regression analysis of
rat sightings with respect to the Rat Czar appointment. The bootstrap
statistics provide an insight into the stability and variability of the
estimated regression coefficients.</p>
<div id="bootstrap-results-1" class="section level3">
<h3>Bootstrap Results:</h3>
<ul>
<li><strong>Intercept (Post_Rat_Czar period) Coefficient</strong>:
<ul>
<li><strong>Original</strong>: 2285.8750</li>
<li><strong>Bias</strong>: 0.4169434</li>
<li><strong>Standard Error</strong>: 167.5870</li>
</ul></li>
<li><strong>Pre_Rat_Czar Coefficient</strong>:
<ul>
<li><strong>Original</strong>: -936.0427</li>
<li><strong>Bias</strong>: -2.5392402</li>
<li><strong>Standard Error</strong>: 172.5642</li>
</ul></li>
</ul>
</div>
<div id="conclusions-from-bootstrap-analysis" class="section level3">
<h3>Conclusions from Bootstrap Analysis</h3>
<p>The bootstrap results indicate that the bias for both coefficients is
small, suggesting that the estimates from our original model are stable
across different samples of our data. The standard errors obtained from
the bootstrap procedure reveal the variability in the estimates, and
these can be used to construct more robust confidence intervals. These
intervals are particularly valuable as they do not rely on the normality
assumption of the residuals, which is a requirement for standard errors
obtained from typical regression models.</p>
<p>This analysis strengthens the reliability of our findings, suggesting
that the Rat Czar’s appointment had a significant impact on rat
sightings, as indicated by the original regression analysis.</p>
</div>
</div>
</div>
<div id="cross-validation-of-rat-czar" class="section level1">
<h1>Cross-Validation of Rat Czar</h1>
<pre class="r"><code>## Define control using k-fold cross-validation
train_control &lt;- trainControl(method = &quot;cv&quot;, number = 10)

# Train the model
model &lt;- train(Sightings ~ Pre_Rat_Czar + Post_Rat_Czar,
               data = merged_data,
               trControl = train_control,
               method = &quot;lm&quot;)

# Summarize the results
print(model)</code></pre>
<pre><code>## Linear Regression 
## 
## 169 samples
##   2 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 152, 152, 152, 152, 153, 151, ... 
## Resampling results:
## 
##   RMSE     Rsquared   MAE     
##   561.037  0.1806282  458.1055
## 
## Tuning parameter &#39;intercept&#39; was held constant at a value of TRUE</code></pre>
<div id="cross-validation-results-for-linear-regression-analysis"
class="section level2">
<h2>Cross-Validation Results for Linear Regression Analysis</h2>
<p>Cross-validation was conducted to assess the model’s predictive
performance.</p>
</div>
<div id="cross-validation-results" class="section level2">
<h2>Cross-Validation Results:</h2>
<ul>
<li><strong>RMSE (Root Mean Squared Error)</strong>: 557.807</li>
<li><strong>R-squared</strong>: 0.1889574</li>
<li><strong>MAE (Mean Absolute Error)</strong>: 459.687</li>
</ul>
</div>
<div id="interpretation-of-cross-validation-results"
class="section level2">
<h2>Interpretation of Cross-Validation Results:</h2>
<p>The RMSE and MAE are measures of the model’s prediction error. The
relatively high values of RMSE (557.807) and MAE (459.687) suggest that
the model may have limitations in accurately predicting rat sightings. A
lower RMSE and MAE would indicate a better fit to the data.</p>
<p>The R-squared value of 0.1889574 implies that the model explains
approximately 18.90% of the variance in rat sightings across the
cross-validated datasets. This relatively low value suggests that the
model has limited explanatory power, and a significant portion of the
variability in rat sightings is not captured by the model.</p>
<p>The presence of missing values in the resampled performance measures
and the modest R-squared value indicate that the model could benefit
from further refinement. Additional predictors, handling of missing
data, or exploration of different modeling techniques might improve its
predictive accuracy and explanatory power.</p>
<p>Overall, while the model provides some insights into factors
influencing rat sightings, these cross-validation results highlight the
need for caution in interpreting the model’s predictions and for further
investigation into other potential contributing factors.</p>
</div>
</div>
<div
id="bootstrap-and-cross-validation-results-for-covid-19-impact-analysis"
class="section level1">
<h1>Bootstrap and Cross-Validation Results for COVID-19 Impact
Analysis</h1>
<div id="bootstrap-analysis-for-covid-19-impact" class="section level2">
<h2>Bootstrap Analysis for COVID-19 Impact</h2>
<pre class="r"><code>## Define the statistic function for bootstrapping
stat_function_covid &lt;- function(data, indices) {
  d &lt;- data[indices, ] # allows bootstrapping to select sample
  fit &lt;- lm(Sightings ~ Pre_Covid + During_Covid, data = d)
  return(coef(fit))
}

## Apply the bootstrapping with R = 1000 bootstrap replicates
bootstrap_results_covid &lt;- boot(data = merged_data, statistic = stat_function_covid, R = 1000)

## Print the results
print(bootstrap_results_covid)</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = merged_data, statistic = stat_function_covid, R = 1000)
## 
## 
## Bootstrap Statistics :
##       original    bias    std. error
## t1*  2285.8750 -8.203824    171.9859
## t2* -1116.1108  9.569559    178.2595
## t3*  -353.1908  7.824894    197.9294</code></pre>
</div>
<div id="cross-validation-for-covid-19-impact" class="section level2">
<h2>Cross-Validation for COVID-19 Impact</h2>
<pre class="r"><code>## Define the control using 10-fold cross-validation
train_control &lt;- trainControl(method = &quot;cv&quot;, number = 10)

## Train the model
model_cv_covid &lt;- train(Sightings ~ Pre_Covid + During_Covid,
                        data = merged_data,
                        trControl = train_control,
                        method = &quot;lm&quot;)

## Summarize the results
print(model_cv_covid)</code></pre>
<pre><code>## Linear Regression 
## 
## 169 samples
##   2 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 152, 151, 152, 150, 153, 153, ... 
## Resampling results:
## 
##   RMSE      Rsquared   MAE     
##   465.3739  0.4217767  379.1727
## 
## Tuning parameter &#39;intercept&#39; was held constant at a value of TRUE</code></pre>
</div>
<div
id="interpretation-of-bootstrap-and-cross-validation-results-for-covid-19-impact-analysis"
class="section level2">
<h2>Interpretation of Bootstrap and Cross-Validation Results for
COVID-19 Impact Analysis</h2>
<p>We performed a bootstrap analysis and cross-validation to assess the
stability and predictive performance of our regression model, which
estimates the impact of the COVID-19 pandemic on rat sightings.</p>
<div id="bootstrap-results-for-covid-19-analysis"
class="section level3">
<h3>Bootstrap Results for COVID-19 Analysis</h3>
<p>The bootstrap analysis provides an estimate of the variability of our
regression coefficients:</p>
<ul>
<li><strong>Intercept (Post-COVID period) Coefficient</strong>:
<ul>
<li><strong>Original</strong>: 2285.8750</li>
<li><strong>Bias</strong>: -8.203824</li>
<li><strong>Standard Error</strong>: 171.9859</li>
</ul></li>
<li><strong>Pre_COVID Coefficient</strong>:
<ul>
<li><strong>Original</strong>: -1116.1108</li>
<li><strong>Bias</strong>: 9.569559</li>
<li><strong>Standard Error</strong>: 178.2595</li>
</ul></li>
<li><strong>During_COVID Coefficient</strong>:
<ul>
<li><strong>Original</strong>: -353.1908</li>
<li><strong>Bias</strong>: 7.824894</li>
<li><strong>Standard Error</strong>: 197.9294</li>
</ul></li>
</ul>
<p>The small biases indicate that our coefficient estimates are robust
and consistent across different samples of the data. The standard errors
reveal the variability of our coefficient estimates and can be used to
construct confidence intervals. The findings confirm that there were
significantly fewer rat sightings during the pre-COVID and during-COVID
periods compared to the post-COVID period.</p>
</div>
<div id="cross-validation-results-for-covid-19-analysis"
class="section level3">
<h3>Cross-Validation Results for COVID-19 Analysis</h3>
<p>Cross-validation was utilized to assess the model’s predictive
performance. The results are as follows:</p>
<ul>
<li><strong>RMSE (Root Mean Squared Error)</strong>: 465.3739</li>
<li><strong>R-squared</strong>: 0.4217767</li>
<li><strong>MAE (Mean Absolute Error)</strong>: 379.1727</li>
</ul>
<p>These measures provide insights into the model’s prediction error and
its explanatory power. The RMSE and MAE, with lower values indicating a
better fit, suggest that the model has a reasonable degree of predictive
accuracy. The R-squared value, indicating that about 42.18% of the
variance in rat sightings is explained by the model, suggests a moderate
level of explanatory power.</p>
<p>However, the still substantial amount of unexplained variance points
to the presence of other factors influencing rat sightings that are not
captured by the model. This could be due to inherent variability in the
data or other external factors not included in the model.</p>
<p>In summary, while the model provides valuable insights into the
impact of the COVID-19 pandemic on rat sightings, it also highlights the
complexity of the issue and the need for further research to fully
understand the underlying dynamics.</p>
<pre class="r"><code># Diagnostic Plots for Rat Czar Model
par(mfrow = c(2, 2))  # Set up the plotting area
plot(model_rat_czar)</code></pre>
<p><img src="regression_final_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code># Durbin-Watson Test for Rat Czar Model
dwtest(model_rat_czar)</code></pre>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  model_rat_czar
## DW = 0.47205, p-value &lt; 2.2e-16
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<pre class="r"><code># Diagnostic Plots for COVID-19 Model
par(mfrow = c(2, 2))  # Set up the plotting area
plot(model_covid)</code></pre>
<p><img src="regression_final_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<pre class="r"><code># Durbin-Watson Test for COVID-19 Model
dwtest(model_covid)</code></pre>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  model_covid
## DW = 0.62416, p-value &lt; 2.2e-16
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
</div>
<div id="diagnostic-analysis-interpretation" class="section level1">
<h1>Diagnostic Analysis Interpretation</h1>
<p>Based on our diagnostic checks, we have some interesting observations
that shed light on our regression models.</p>
<div id="observations-from-diagnostic-plots" class="section level2">
<h2>Observations from Diagnostic Plots:</h2>
<ul>
<li><p>The <strong>Residuals vs Fitted</strong> plots for both the Rat
Czar and COVID-19 models demonstrate a reasonable spread around the
horizontal axis. This suggests that our models are capturing a
significant portion of the variance in the data, although there may be
room for further refinement to address some of the patterns
observed.</p></li>
<li><p>In the <strong>Q-Q Plots</strong>, we notice some deviation from
normality in the tails for both models. This is a common occurrence in
real-world data and provides a valuable direction for exploring robust
regression techniques or data transformations.</p></li>
<li><p>The <strong>Scale-Location</strong> plots indicate that our
residuals might not be perfectly homoscedastic. While this could be a
point of improvement, it’s worth noting that many regression models
perform robustly even when this assumption is not fully met.</p></li>
<li><p><strong>Residuals vs Leverage</strong> plots help us identify a
few points with higher leverage. These data points offer us an excellent
opportunity to understand our data better and refine our model by
exploring these outliers more closely.</p></li>
</ul>
</div>
<div id="insights-from-durbin-watson-test" class="section level2">
<h2>Insights from Durbin-Watson Test:</h2>
<ul>
<li>The Durbin-Watson test results for both models suggest the presence
of autocorrelation in the residuals. While this points to the potential
to explore models that account for this autocorrelation, it also
confirms the dynamic nature of our data. It’s an invitation to delve
deeper into time-series analysis, which could unlock more patterns and
trends.</li>
</ul>
</div>
<div id="overall-conclusion-1" class="section level2">
<h2>Overall Conclusion:</h2>
<p>The results of our regression analysis are promising, showing that
our models are capable of capturing key trends in the data. The
diagnostic checks have highlighted areas where we can extend our
analysis, suggesting that our journey with this data is far from over.
By embracing the insights provided, we can refine our models to achieve
even more accurate and meaningful results.</p>
<p>Our analysis stands as a robust foundation for understanding the
impact of the Rat Czar’s appointment and the COVID-19 pandemic on rat
sightings. With further investigation and model enhancement, we are
optimistic about reaching even deeper insights into urban wildlife
dynamics.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
